---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: demo
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      pv: pv-test
