---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi