apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: dev

components:
- ../components/prometheus

images:
- name: helloworld
  newName: k3d-registry.127.0.0.1.nip.io:5000/helloworld
  newTag: v0.1.0

patches:
- path: secret.yaml
- path: configmap.yaml

replacements: 
  - path: replacement.yaml