apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
data:
  NAME: WORLD2
kind: ConfigMap
metadata:
  name: helloworld-config
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: helloworld-secret
  namespace: demo
stringData:
  SECRETNAME: DLROW
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-lb
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - envFrom:
        - configMapRef:
            name: helloworld-config
        - secretRef:
            name: helloworld-secret
        image: k3d-registry.127.0.0.1.nip.io:5000/helloworld:v0.1.0
        name: helloworld
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
